---
- name: Restart Homepage
  ansible.builtin.shell:
    cmd: "docker compose up -d --remove-orphans"
    chdir: "{{ docker_config_dir }}/homepage"

- name: Restart Jellyfin
  ansible.builtin.shell:
    cmd: "docker compose up -d --remove-orphans"
    chdir: "{{ docker_config_dir }}/jellyfin"
